### ISSUE TITLE
Support XDG spec, or at least an environment variable to customize ~/.localhost path

### ISSUE THREAD

**Issue by nogweii** [socketry/localhost#27]
I'd prefer to limit the number of dotfiles in my $HOME, so I'd like to move ~/.localhost/ to a different path, possibly ~/.local/state/localhost/ or similar.

That could be done following the [XDG standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (`$XDG_STATE_HOME` seems appropriate), or support a specific environment variable, like `$LOCALHOST_AUTHORTIY_PATH`.

What do you think?

**Comment by ioquatix** [comment]
I think it's a good idea and I think your suggestion to default to `~/.local/state/localhost` is a good idea (or maybe `localhost-ruby` or something more specific if we think the current is too generic).

Do you want to open a PR?

**Comment by nogweii** [comment]
I can open a PR soon, yeah.

Is there a backwards compatibility concern? What should happen to users with an existing `~/.localhost` directory? I see a few options:

1. Ignore it
2. Prefer it, if it exists
3. Move it to the new directory

**Comment by ioquatix** [comment]
I would suggest (3) makes the most sense to me.
