### ISSUE TITLE
Is `verify_hostname` useful?

### ISSUE THREAD

**Issue by ioquatix** [socketry/localhost#3]
@tarcieri I was wondering if you'd check this as I admire your work on Ruby's OpenSSL implementation.

https://github.com/socketry/localhost/blob/491348ccf4cde39e43f95a6801a4ba78547207e4/lib/localhost/authority.rb#L94-L121

Do you think those contexts are set up correctly? Do you have any suggestions/ideas?

**Comment by tarcieri** [comment]
Are you trying to issue a cert for localhost using some sort of localhost CA? If so I think "localhost" should still be honored as a SAN

**Comment by ioquatix** [comment]
We create a self-signed root certificate, but it turns out OpenSSL won't accept that unless it's also a CA. I guess we could generate a CA root separately but it just makes everything more complicated for very little benefit.

What does "SAN" stand for in this context?

**Comment by ioquatix** [comment]
I added a SAN for localhost, and it seemed to work better.

**Comment by tarcieri** [comment]
@ioquatix sounds like you figured out SANs.

For this purpose, there's something I'd strongly recommend, and here's why:

When you mint a CA and put it in your truststore, it can be used to impersonate any site.

An alternative is to mint an ephemeral CA, have it issue a single cert with a SAN of `localhost` (or `localhost` and `*.localhost` if you'd like to do subdomain routing), and then forget the CA key. Keep the pubkey around though.

If you do this, then the CA you created for localhost certificates can't be further abused to issue other certs.

**Comment by ioquatix** [comment]
That makes total sense.

I this case, I made a self-signed root certificate, and I set CA:FALSE which I assume means it can't be used to make any more certs.

https://github.com/socketry/localhost/blob/de8964b6fe639e6638089095ec802ac26a8e7b14/lib/localhost/authority.rb#L68-L96

**Comment by tarcieri** [comment]
I'd think you'd want an ephemeral CA and a leaf it signs for maximum compatibility
