### ISSUE TITLE
The example in the README

### ISSUE THREAD

**Issue by peterc** [socketry/localhost#4]
Is it meant to be `peer.puts "Writing..."` so that it actually goes across the "wire" as it were?

Also, could an example be added of using this for HTTPS?

I'm keen to link this in Ruby Weekly but feel some readers might trip up on the example.

**Comment by ioquatix** [comment]
Okay, I've improved the example in the README, and I've also added an example of how to make a HTTPS web server. Can you check it out and let me know if further improvements would be useful?

**Comment by peterc** [comment]
Yes, that seems to work alright - thanks! :)
